public  class ArthimaticCalculations {
    public void addition(integer x, integer y) {
        integer z= x + y;
        system.debug('the result equals to' + z);
    }
    public void substraction(integer x, integer y){
        integer z= x - y;
        system.debug('the result equals to' +z);

    }
    public void multiplication(integer x,integer y,integer m){
        integer z=x*y*m;
        system.debug('the result equals to' +z);
    }
}